# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
PCH = src/util/pch.h
PCH_PLACEHOLDER = $(OBJDIR)/$(notdir $(PCH))
GCH = $(PCH_PLACEHOLDER).gch
INCLUDES += -Isrc -Iassets -Ivendor -I. -Ivendor/glm -Ivendor/glfw/include -Ivendor/imgui -Ivendor/imgui/backends -Ivendor/stb_image -I/usr/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x64)
TARGETDIR = bin/Debug-linux-x86_64/application_template
TARGET = $(TARGETDIR)/application_template
OBJDIR = bin-int/Debug-linux-x86_64/application_template
DEFINES += -DENGINE_INSTALL_DIR=\"/home/mich/workspace/application_template/bin/Debug-linux-x86_64\" -DOUTPUTS=\"Debug-linux-x86_64\" -D_CRT_SECURE_NO_WARNINGS -DGLFW_INCLUDE_NONE -DPLATFORM_LINUX -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -msse4.1 -fPIC -Wall -Wno-dangling-else
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++20 -msse4.1 -fPIC -Wall -Wno-dangling-else
LIBS += vendor/imgui/bin/Debug-linux-x86_64/imgui/libimgui.a -lassimp -lGLEW -lGL -lglfw3 -lQt5Core -lQt5Widgets -lQt5Gui
LDDEPS += vendor/imgui/bin/Debug-linux-x86_64/imgui/libimgui.a
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/imgui/bin/Debug-linux-x86_64/imgui -Lvendor/glfw/build/src -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/qt5 -L/usr/lib64 -m64

else ifeq ($(config),relwithdebinfo_x64)
TARGETDIR = bin/RelWithDebInfo-linux-x86_64/application_template
TARGET = $(TARGETDIR)/application_template
OBJDIR = bin-int/RelWithDebInfo-linux-x86_64/application_template
DEFINES += -DENGINE_INSTALL_DIR=\"/home/mich/workspace/application_template/bin/RelWithDebInfo-linux-x86_64\" -DOUTPUTS=\"RelWithDebInfo-linux-x86_64\" -D_CRT_SECURE_NO_WARNINGS -DGLFW_INCLUDE_NONE -DPLATFORM_LINUX -DRELEASE_WITH_DEBUG_INFO
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -g -msse4.1 -fPIC -Wall -Wno-dangling-else
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -g -std=c++20 -msse4.1 -fPIC -Wall -Wno-dangling-else
LIBS += vendor/imgui/bin/RelWithDebInfo-linux-x86_64/imgui/libimgui.a -lassimp -lGLEW -lGL -lglfw3 -lQt5Core -lQt5Widgets -lQt5Gui
LDDEPS += vendor/imgui/bin/RelWithDebInfo-linux-x86_64/imgui/libimgui.a
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/imgui/bin/RelWithDebInfo-linux-x86_64/imgui -Lvendor/glfw/build/src -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/qt5 -L/usr/lib64 -m64

else ifeq ($(config),release_x64)
TARGETDIR = bin/Release-linux-x86_64/application_template
TARGET = $(TARGETDIR)/application_template
OBJDIR = bin-int/Release-linux-x86_64/application_template
DEFINES += -DENGINE_INSTALL_DIR=\"/home/mich/workspace/application_template/bin/Release-linux-x86_64\" -DOUTPUTS=\"Release-linux-x86_64\" -D_CRT_SECURE_NO_WARNINGS -DGLFW_INCLUDE_NONE -DPLATFORM_LINUX -DRELEASE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -msse4.1 -fPIC -Wall -Wno-dangling-else
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20 -msse4.1 -fPIC -Wall -Wno-dangling-else
LIBS += vendor/imgui/bin/Release-linux-x86_64/imgui/libimgui.a -lassimp -lGLEW -lGL -lglfw3 -lQt5Core -lQt5Widgets -lQt5Gui
LDDEPS += vendor/imgui/bin/Release-linux-x86_64/imgui/libimgui.a
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/imgui/bin/Release-linux-x86_64/imgui -Lvendor/glfw/build/src -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/qt5 -L/usr/lib64 -m64 -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/GL_renderer.o
GENERATED += $(OBJDIR)/UUID.o
GENERATED += $(OBJDIR)/application.o
GENERATED += $(OBJDIR)/buffer.o
GENERATED += $(OBJDIR)/config.o
GENERATED += $(OBJDIR)/crash_handler.o
GENERATED += $(OBJDIR)/dashboard.o
GENERATED += $(OBJDIR)/deletion_queue.o
GENERATED += $(OBJDIR)/entry_point.o
GENERATED += $(OBJDIR)/image.o
GENERATED += $(OBJDIR)/imgui_config.o
GENERATED += $(OBJDIR)/imgui_markdown.o
GENERATED += $(OBJDIR)/io.o
GENERATED += $(OBJDIR)/logger.o
GENERATED += $(OBJDIR)/math.o
GENERATED += $(OBJDIR)/pannel_collection.o
GENERATED += $(OBJDIR)/path_manipulation.o
GENERATED += $(OBJDIR)/pch.o
GENERATED += $(OBJDIR)/random.o
GENERATED += $(OBJDIR)/serializer_binary.o
GENERATED += $(OBJDIR)/serializer_yaml.o
GENERATED += $(OBJDIR)/stopwatch.o
GENERATED += $(OBJDIR)/string_manipulation.o
GENERATED += $(OBJDIR)/system.o
GENERATED += $(OBJDIR)/type_deletion_queue.o
GENERATED += $(OBJDIR)/util.o
GENERATED += $(OBJDIR)/window.o
OBJECTS += $(OBJDIR)/GL_renderer.o
OBJECTS += $(OBJDIR)/UUID.o
OBJECTS += $(OBJDIR)/application.o
OBJECTS += $(OBJDIR)/buffer.o
OBJECTS += $(OBJDIR)/config.o
OBJECTS += $(OBJDIR)/crash_handler.o
OBJECTS += $(OBJDIR)/dashboard.o
OBJECTS += $(OBJDIR)/deletion_queue.o
OBJECTS += $(OBJDIR)/entry_point.o
OBJECTS += $(OBJDIR)/image.o
OBJECTS += $(OBJDIR)/imgui_config.o
OBJECTS += $(OBJDIR)/imgui_markdown.o
OBJECTS += $(OBJDIR)/io.o
OBJECTS += $(OBJDIR)/logger.o
OBJECTS += $(OBJDIR)/math.o
OBJECTS += $(OBJDIR)/pannel_collection.o
OBJECTS += $(OBJDIR)/path_manipulation.o
OBJECTS += $(OBJDIR)/pch.o
OBJECTS += $(OBJDIR)/random.o
OBJECTS += $(OBJDIR)/serializer_binary.o
OBJECTS += $(OBJDIR)/serializer_yaml.o
OBJECTS += $(OBJDIR)/stopwatch.o
OBJECTS += $(OBJDIR)/string_manipulation.o
OBJECTS += $(OBJDIR)/system.o
OBJECTS += $(OBJDIR)/type_deletion_queue.o
OBJECTS += $(OBJDIR)/util.o
OBJECTS += $(OBJDIR)/window.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking application_template
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning application_template
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/application.o: src/application.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_config.o: src/config/imgui_config.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dashboard.o: src/dashboard/dashboard.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/entry_point.o: src/entry_point.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/window.o: src/platform/window.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/buffer.o: src/render/buffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/image.o: src/render/image.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GL_renderer.o: src/render/open_GL/GL_renderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crash_handler.o: src/util/crash_handler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UUID.o: src/util/data_structures/UUID.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/deletion_queue.o: src/util/data_structures/deletion_queue.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/path_manipulation.o: src/util/data_structures/path_manipulation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/string_manipulation.o: src/util/data_structures/string_manipulation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/type_deletion_queue.o: src/util/data_structures/type_deletion_queue.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/config.o: src/util/io/config.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/io.o: src/util/io/io.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/logger.o: src/util/io/logger.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/serializer_binary.o: src/util/io/serializer_binary.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/serializer_yaml.o: src/util/io/serializer_yaml.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/math.o: src/util/math/math.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/random.o: src/util/math/random.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pch.o: src/util/pch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/system.o: src/util/system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stopwatch.o: src/util/timing/stopwatch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_markdown.o: src/util/ui/imgui_markdown.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pannel_collection.o: src/util/ui/pannel_collection.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/util.o: src/util/util.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif