name: Cross-Platform Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, fedora-latest]              # Option 0
        os: [ubuntu-latest, fedora-40]                  # Option 1
        # os: [ubuntu-latest, centos-stream-9]          # Option 2
        # os: [ubuntu-latest, rocky-linux-9]            # Option 3
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Show Linux version
        run: |
          echo "========= OS VERSION ========="
          cat /etc/os-release || true
          echo "========= KERNEL VERSION ========="
          uname -a
          echo "========= SHELL VERSION ========="
          echo $SHELL --version
          
      - name: Basic system test
        run: echo "Successfully ran on ${{ matrix.os }}"

  windows-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Show Windows version
        run: |
          echo "========= WINDOWS VERSION ========="
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
          echo "========= POWERSHELL VERSION ========="
          pwsh --version
          
      - name: Basic system test
        run: Write-Host "Successfully ran on Windows"
