name: Linux Compatibility Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, fedora-latest]              # Option 0
        os: [ubuntu-latest, fedora-40]                  # Option 1
        # os: [ubuntu-latest, centos-stream-9]          # Option 2
        # os: [ubuntu-latest, rocky-linux-9]            # Option 3

    steps:
      # checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Debug OS info
      - name: Verify OS
        run: |
          cat /etc/os-release
          echo "Running on: ${{ matrix.os }}"

      # testing setup script execution here later
      # - name: Run Setup Script
      #   run: ./setup.py